### PR TITLE
[COLAB-925] analytics

### PR DESCRIPTION
**Pull request by carlosbpf**
I added a new utility class to send async events to google analytics and added the calls to the services where needed. The new implementation now needs a key, that is found using platformkey attributes.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/35)

### CODE REVIEW

**Comment by jobachh** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalMemberRatingClient.java, line 6 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRnkXgVeTVSjImkI45:-KuRnkXhE7y8g06RAQiF:b5e9m6z) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalMemberRatingClient.java#L6)):*
> ```Java
> import org.xcolab.client.activities.enums.ActivityProvidersType;
> import org.xcolab.client.activities.helper.ActivityEntryHelper;
> import org.xcolab.client.admin.attributes.platform.PlatformAttributeKey;
> ```

I think this is unused now, since there is only a spacing change below

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java, line 208 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRp1h0XLW6sXtAtBBw:-KuRp1h0XLW6sXtAtBBx:bndl88t) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java#L208)):*
> ```Java
>         }
>         if (roleName != null) {
>             query.addConditions(memberCategory.DISPLAY_NAME.eq(roleName));
> ```

This somehow snuck in from a different pull request/branch, but I'm guessing it'll go away as soon as the other PR is merged. Make sure you branch from develop.

---

*[view/src/main/java/org/xcolab/view/pages/loginregister/LoginRegisterService.java, line 122 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRnwPth5AJinhpDBwy:-KuRnwPth5AJinhpDBwz:bh82e37) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/pages/loginregister/LoginRegisterService.java#L122)):*
> ```Java
> 
>         if(PlatformAttributeKey.ANALYTICS_PRIVATE_KEY_PATH.isPresent()){
>             if(fbIdString==null && googleId==null){
> ```

This could use a reformatting (horizontal spacing between operators/parenthesis/braces)

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/action/SupportProposalActionController.java, line 63 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRoPGEab1BXtBE7_3Y:-KuRoPGEab1BXtBE7_3Z:b3igf2j) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/pages/proposals/view/action/SupportProposalActionController.java#L63)):*
> ```Java
>                 if(PlatformAttributeKey.ANALYTICS_PRIVATE_KEY_PATH.isPresent()) {
>                     GoogleAnalyticsUtils.pushEventAsync(GoogleAnalyticsEventType.CONTEST_ENTRY_SUPPORT);
>                 }
> ```

The check could be nicely extracted into a separate method that only reports the event if the key is set (also - note the horizontal spacing as above)

---

*[view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java, line 56 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRonzSnkxj405-b0gy:-KuRonzSnkxj405-b0gz:bf01r7c) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java#L56)):*
> ```Java
>             GenericUrl url = new GenericUrl(GOOGLE_ANALYTICS_URL);
>             httpRequest.setUrl(url);
>             url.put("v", "1");
> ```

Can we turn this into a constant?

---

*[view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java, line 58 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRollIsEzYs0JBeoy-:-KuRollIsEzYs0JBeoy0:bhu65sf) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java#L58)):*
> ```Java
>             url.put("v", "1");
>             url.put("tid", GOOGLE_ANALYTICS_KEY);
>             url.put("cid", "555");
> ```

What is this constant for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Comment by jobachh** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java, line 56 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRonzSnkxj405-b0gy:-KueiqamJiOjZ_7V-Js1:bna4dp1) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java#L56)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

Can we turn this into a constant?
</blockquote></details>

Nice! I like the new constants :+1: 

---

*[view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx, line 67 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KueiTjT4Gq2ryrhnIuF:-KueiTjT4Gq2ryrhnIuG:bt8gc7g) ([raw file](https://github.com/cci-mit/xcolab/blob/04e534f4067a523984834ce30275ae70579e3e52/view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx#L67)):*
> ```
> 
>             <form:hidden path="language" />
> ```

@carlosbpf this looks like an unrelated change and I think it might break if i18n is active since then there will be two forms that map to the same path (the language select being the other).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Comment by jobachhu** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx, line 67 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KueiTjT4Gq2ryrhnIuF:-Kv4ETJkOeOf4S4XKyAY:byy7xlo) ([raw file](https://github.com/cci-mit/xcolab/blob/04e534f4067a523984834ce30275ae70579e3e52/view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx#L67)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

@carlosbpf this looks like an unrelated change and I think it might break if i18n is active since then there will be two forms that map to the same path (the language select being the other).
</blockquote></details>

@carlosbpf Can you take a look at this? I'm worried this unrelated change might break i18n

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Comment by jobachhu** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx, line 67 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KueiTjT4Gq2ryrhnIuF:-KwXF6snlb0ejCKq_SUe:bpewmdy) ([raw file](https://github.com/cci-mit/xcolab/blob/04e534f4067a523984834ce30275ae70579e3e52/view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx#L67)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

@carlosbpf Can you take a look at this? I'm worried this unrelated change might break i18n
</blockquote></details>

@carlosbpf is this comment addressed? It looks like the change is still part of the pull request. Make sure you respond to *all* comments by either saying that they were completed or explaining why not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Comment by carlosbpf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java, line 58 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KuRollIsEzYs0JBeoy-:-KuUX8UndCKvokVFXo3o:b3687c5) ([raw file](https://github.com/cci-mit/xcolab/blob/ff7f65e41f27ba049853eea5ae5d10d8acc729c2/view/src/main/java/org/xcolab/view/util/googleanalytics/GoogleAnalyticsUtils.java#L58)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

What is this constant for?
</blockquote></details>

This is the client id, if we had lots, I just left the default value from the google documentation.

---

*[view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx, line 67 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/35#-KueiTjT4Gq2ryrhnIuF:-Kx7-lWJBbWrXsy1bz-Y:b-xa755l) ([raw file](https://github.com/cci-mit/xcolab/blob/04e534f4067a523984834ce30275ae70579e3e52/view/src/main/webapp/WEB-INF/jsp/loginregister/register.jspx#L67)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

@carlosbpf is this comment addressed? It looks like the change is still part of the pull request. Make sure you respond to *all* comments by either saying that they were completed or explaining why not.
</blockquote></details>

just undid the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Comment by jobachhu** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/35)*

**Pull request merged**
