### PR TITLE
[COLAB-2408] Fix section copying when moving proposals

### PR DESCRIPTION
**Pull request by jobachhu**
This PR fixes the proposal-contest mapping when copying a proposal. The context proposal did not previously reference the context contest (i.e. the target contest), but did instead reference the source contest. This lead to a problem with checking if the sections changed.

~Depends on #69.~

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/70)

### CODE REVIEW

**Comment by umov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java, line 169 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/70#-Kz0VWswWgEkfDK_-98H:-Kz0VWswWgEkfDK_-98I:bjvtks1) ([raw file](https://github.com/cci-mit/xcolab/blob/046b1bd646574fa06e851bfc090a82ce559b70ee/view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java#L169)):*
> ```Java
>             try {
>                 Proposal proposal = proposalClient.getProposal(givenProposalId);
>                 return new Proposal(proposal, contest);
> ```

I don't really like this code style of having the `return` here. When you look at the bottom of method to find out what it returns, you see the `null` and have to dig into the method body to understand what's going on. So I think it's preferable to do `proposal = new Proposal(proposal, contest);` here and return proposal at the bottom (as it was before).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/70)*

**Comment by jobachhu** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java, line 169 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/70#-Kz0VWswWgEkfDK_-98H:-Kz0ZQZ9wikAaNlExrTK:b-kzo109) ([raw file](https://github.com/cci-mit/xcolab/blob/046b1bd646574fa06e851bfc090a82ce559b70ee/view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java#L169)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

I don't really like this code style of having the `return` here. When you look at the bottom of method to find out what it returns, you see the `null` and have to dig into the method body to understand what's going on. So I think it's preferable to do `proposal = new Proposal(proposal, contest);` here and return proposal at the bottom (as it was before).
</blockquote></details>

You're right, it's a bit confusing to read that way. Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/70)*

**Comment by umov** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/70#-:-Kz0a5Aj8-kLVQktvGP5:bnfp4nl)*

**Comment by umov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/70)*

**Pull request merged**
