### PR TITLE
[COLAB-2559] Replace c-TabBar with bootstrap nav-tabs

### PR DESCRIPTION
**Pull request by cwoebker**
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/128)

### CODE REVIEW

**Comment by jobachhu** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[view/src/main/resources/static/sass/bootstrap/custom/_badges.scss, line 3 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9pyQp4B56reE2LQAKS:-L9pyQp4B56reE2LQAKT:b-2d3txa) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/resources/static/sass/bootstrap/custom/_badges.scss#L3)):*
> ```SCSS
> @import "bootstrap/variables";
> 
> .cb-badge-margin-left {
> ```

I would replace this class. There are two options:
1) Bootstrap has some spacing utilities, which do just what this class does. Here you could use `ml-2` (applies `margin-left: 0.5rem`). See https://getbootstrap.com/docs/4.0/utilities/spacing
2) Create a generic rule for badges in tabs. I think the badges would always be to the right of the tab and that we'd always want this spacing. Something like this:
```
.nav-item .badge {
  margin-left: 0.5rem
}
```

I'm leaning towards Option 2. What do you think?

---

*[view/src/main/resources/static/sass/bootstrap/custom/_badges.scss, line 4 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9pt6ltEH_yu9own2NK:-L9pt6ltEH_yu9own2NL:b-yaa60f) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/resources/static/sass/bootstrap/custom/_badges.scss#L4)):*
> ```SCSS
> 
> .cb-badge-margin-left {
>   margin-left: 5px;
> ```

This isn't really documented yet, but we now mostly use `1rem` (equivalent to `8px`) as spacing between small elements and `1rem` (equivalent to `16px`) for larger spacing.

---

*[view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/header.jspx, line 49 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9psvvLCb34VEYJ3tCj:-L9psvvLCb34VEYJ3tCk:bdqcjqg) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/header.jspx#L49)):*
> ```
>         </c:if>
>         <c:if test="${tabs.size() > 0}">
>             <ul class="nav nav-tabs flex-column flex-md-row clearfix">
> ```

You can most likely remove the `clearfix` class.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cci-mit/xcolab/128)*

**Comment by cwoebker** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[view/src/main/resources/static/sass/bootstrap/custom/_badges.scss, line 3 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9pyQp4B56reE2LQAKS:-LAVOOIk7-OulGXCyBjY:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/resources/static/sass/bootstrap/custom/_badges.scss#L3)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

I would replace this class. There are two options:
1) Bootstrap has some spacing utilities, which do just what this class does. Here you could use `ml-2` (applies `margin-left: 0.5rem`). See https://getbootstrap.com/docs/4.0/utilities/spacing
2) Create a generic rule for badges in tabs. I think the badges would always be to the right of the tab and that we'd always want this spacing. Something like this:
```
.nav-item .badge {
  margin-left: 0.5rem
}
```

I'm leaning towards Option 2. What do you think?
</blockquote></details>

Done.

---

*[view/src/main/resources/static/sass/bootstrap/custom/_badges.scss, line 4 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9pt6ltEH_yu9own2NK:-LAVOOku9jdPYmJjf0OI:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/resources/static/sass/bootstrap/custom/_badges.scss#L4)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This isn't really documented yet, but we now mostly use `1rem` (equivalent to `8px`) as spacing between small elements and `1rem` (equivalent to `16px`) for larger spacing.
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/header.jspx, line 49 at r2](https://beta.reviewable.io/reviews/cci-mit/xcolab/128#-L9psvvLCb34VEYJ3tCj:-LAVOPuD4aAnsMld03Jf:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/4d38e647d3a3cfbde09e5dcbf9626fee9d661ddb/view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/header.jspx#L49)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

You can most likely remove the `clearfix` class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cci-mit/xcolab/128)*

**Comment by cwoebker** [comment]
@jobachhu You can check out some of the new changes, there are some minor occurrences of c-Tabbar left.

**Comment by jobachhu** [comment]
This is looking great! Looking forward to merging this soon :)

---

Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[view/src/main/resources/static/sass/partials/pages/_proposals.scss, line 4 at r3](https://reviewable.io/reviews/cci-mit/xcolab/128#-LArTg2hDJuTpCnoVnpC:-LArTg2hDJuTpCnoVnpD:bq25pr4) ([raw file](https://github.com/cci-mit/xcolab/blob/acf8c0b589a02209a9456303135bc7588e3e2ee9/view/src/main/resources/static/sass/partials/pages/_proposals.scss#L4)):*
> ```SCSS
> @import "bootstrap/mixins/caret";
> 
> $p-proposal__header__background: url(/images/pattern-6x6-blue.png) !default;
> ```

This variable is now unused. You can probably also delete the image (do a search to make sure it isn't used elsewhere first).

Also do a search to check if this variable is set in any of the other themes - if yes, then you can delete it there as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/128#-:-LArTsOIA34VWrqovIuK:b-tz5mi4)*

**Comment by cwoebker** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/resources/static/sass/partials/pages/_proposals.scss, line 4 at r3](https://reviewable.io/reviews/cci-mit/xcolab/128#-LArTg2hDJuTpCnoVnpC:-LAxw5HKBD9TSul9yp9t:b5hpsh1) ([raw file](https://github.com/cci-mit/xcolab/blob/acf8c0b589a02209a9456303135bc7588e3e2ee9/view/src/main/resources/static/sass/partials/pages/_proposals.scss#L4)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This variable is now unused. You can probably also delete the image (do a search to make sure it isn't used elsewhere first).

Also do a search to check if this variable is set in any of the other themes - if yes, then you can delete it there as well.
</blockquote></details>

The image is also used in modeling.scss:

#impact .shaded-bg {
  background: url(/images/pattern-6x6-blue.png);
}

I removed the variable.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/128)*

**Pull request merged**
