### PR TITLE
[COLAB-2202] role member search

### PR DESCRIPTION
**Pull request by carlosbpf**
Now this is ok.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/33)

### CODE REVIEW

**Comment by jobachh** [comment]
Good catch on the aliases not being set correctly and nice fix!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KuLYQXhskzJYfA0iStl:-KuLYQXhskzJYfA0iStm:b-yfla25) (no related file):*
One thing I was thinking is that since we've had a lot of problems with this in the past and it's a quite complex method, it would probably be good to add some tests. We already have some very simple MemberDao tests, can you add tests (and test data) to check if the lists of roles are being retrieved correctly?

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java, line 10 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KuLUisjMSIdo9jZ6Z7A:-KuLUisjMSIdo9jZ6Z7B:b-i58yrg) ([raw file](https://github.com/cci-mit/xcolab/blob/e8092387e595e97c76e58bc1beba312bf2e79e2a/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java#L10)):*
> ```Java
> import org.jooq.SelectQuery;
> import org.jooq.impl.DSL;
> import org.jooq.impl.TableImpl;
> ```

This import and `Users_Roles` below are unused (removing them will make the Codacy check happy too :smile:  )

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java, line 90 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KuLXJEQf5HBMi2w5Vf5:-KuLXJEQf5HBMi2w5Vf6:b-i6v8ou) ([raw file](https://github.com/cci-mit/xcolab/blob/e8092387e595e97c76e58bc1beba312bf2e79e2a/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java#L90)):*
> ```Java
>         if (roleName != null) {
>             Users_RolesTable uc = USERS_ROLES.as("ur");
>             MemberCategoryTable mc = MEMBER_CATEGORY.as("mc");
> ```

Let's use full names as variable names (`userRoles`, `memberCategory`), that makes the query below a little easier to read. Since these aliases/variables already exist on the outer layer, you can add a suffix (maybe just a number or something like `inner` because it's in the inner query).

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java, line 98 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KuLXhFaZq4EYeC53kaE:-KuLXhFaZq4EYeC53kaF:b-83sjoh) ([raw file](https://github.com/cci-mit/xcolab/blob/e8092387e595e97c76e58bc1beba312bf2e79e2a/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java#L98)):*
> ```Java
>                     .where(uc.USER_ID.eq(member.ID_))
>                     .orderBy(mc.SORT_ORDER.desc())
>                     .limit(0,1)
> ```

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-:-KuLYIRIvUsvg187S4QP:bk87n36)*

**Comment by jobachhu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[microservices/services/members-service/src/test/java/org/xcolab/service/members/domain/member/MemberDaoTest.java, line 57 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KvgbmJHxmNTMs9wjk0Y:-KvgbmJHxmNTMs9wjk0Z:baavjgp) ([raw file](https://github.com/cci-mit/xcolab/blob/b73ce0e2c5101170219a1a2f1ecdbb2f4125474e/microservices/services/members-service/src/test/java/org/xcolab/service/members/domain/member/MemberDaoTest.java#L57)):*
> ```Java
>                 memberDao.findByGiven(PaginationHelper.EVERYTHING, "admin", null,
>                         "Member", null, null, null, null, null);
>         assertEquals("Wrong number of members with role:Member", 1, members.size());
> ```

If you are searching for the role member with the current data, the expected number should be two as there are two members, who have the role member as the highest visible role and are not deleted. The reason you're only getting one is because you're also filtering for the name "admin" above, which there is only one of (essentially making this test a copy of the test above). The test should only do one thing, i.e. it should not also be filtering for the name "admin". Can you correct the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/33)*

**Comment by carlosbpf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KuLYQXhskzJYfA0iStl:-Kx70ulBqYXaO2G0aU0m:bb7oryy) (no related file):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

One thing I was thinking is that since we've had a lot of problems with this in the past and it's a quite complex method, it would probably be good to add some tests. We already have some very simple MemberDao tests, can you add tests (and test data) to check if the lists of roles are being retrieved correctly?
</blockquote></details>

sure

---

*[microservices/services/members-service/src/test/java/org/xcolab/service/members/domain/member/MemberDaoTest.java, line 57 at r2](https://reviewable.io:443/reviews/cci-mit/xcolab/33#-KvgbmJHxmNTMs9wjk0Y:-Kx70w5kyylVrXofYJ7B:bjez9eh) ([raw file](https://github.com/cci-mit/xcolab/blob/b73ce0e2c5101170219a1a2f1ecdbb2f4125474e/microservices/services/members-service/src/test/java/org/xcolab/service/members/domain/member/MemberDaoTest.java#L57)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

If you are searching for the role member with the current data, the expected number should be two as there are two members, who have the role member as the highest visible role and are not deleted. The reason you're only getting one is because you're also filtering for the name "admin" above, which there is only one of (essentially making this test a copy of the test above). The test should only do one thing, i.e. it should not also be filtering for the name "admin". Can you correct the test?
</blockquote></details>

Did it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/33)*

**Comment by jobachhu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/33)*

**Pull request merged**
