### PR TITLE
[COLAB-2088] Linkify URLs in User Bio

### PR DESCRIPTION
**Pull request by umov**
This PR implements the URL linkification on user bio submission.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/19)

### CODE REVIEW

**Comment by jobachh** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[microservices/util/xcolab-utils/pom.xml, line 122 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuRDZe7otcFYx12iqv:-KsuRDZe7otcFYx12iqw:b-bpwlhw) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/pom.xml#L122)):*
> ```XML
>             <groupId>org.nibor.autolink</groupId>
>             <artifactId>autolink</artifactId>
>             <version>${autolink.version}</version>
> ```

You can omit the version here - it's inherited from the `dependencyManagement` tag in the root `pom.xml`.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuUP6HRFul9OE_2mIz:-KsuUP6HRFul9OE_2mJ-:bdqpvpd) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L25)):*
> ```Java
> public final class HtmlUtil {
> 
>     private static final String EXISTING_LINKS_REGEX = "(<a[^>]*>[^<]*</a>|]*>|<a[^>]*>)";
> ```

I think if you parse an anchor tag that contains a link within a nested html tag, this regex might not match the second URL since the opening `<` of the nested html tag would fail the regex (this could be solved by using a wildcard with a greedy quantifier, something like `<a[^>]*>.*?</a>`).

This could also be a nice edge case for unit tests:
```html
<a href="www.google.com"><b>www.google.com</b></a>
```

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 26 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuTcsVhT7e5fFiQTVw:-KsuTcsVhT7e5fFiQTVx:b-luzrk3) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L26)):*
> ```Java
> 
>     private static final String EXISTING_LINKS_REGEX = "(<a[^>]*>[^<]*</a>|]*>|<a[^>]*>)";
>     private static final Pattern existingLinksPattern = Pattern.compile(EXISTING_LINKS_REGEX);
> ```

Good call extracting this into a constant :+1:  Compiling `Pattern`s is expensive!

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 100 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuSdBMLrdAC5CjBbCe:-KsuSdBMLrdAC5CjBbCf:bhhh22c) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L100)):*
> ```Java
>         LinkExtractor linkExtractor = LinkExtractor.builder()
>                 .linkTypes(EnumSet.of(LinkType.URL, LinkType.WWW))
>                 .build();
> ```

I'm not sure how it's designed, but it seems like this could potentially be extracted into a `static final` field (if the `LinkExtractor` class is thread-safe or immutable).

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 129 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuTR0Fn5itgnI-FbHz:-KsuTR0Fn5itgnI-FbI-:b-d2xabc) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L129)):*
> ```Java
>      * @return Input HTML string with URLs converted to HTML links.
>      */
>     public static String linkifyUrlsInHtml(String content) {
> ```

I like the design choice of splitting this into two methods - well done!

---

*[microservices/util/xcolab-utils/src/test/java/org/xcolab/util/html/HtmlUtilTest.java, line 7 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuS-O6lwx0ot_9IidQ:-KsuS-O70QHSJg_SCcKK:bksivj0) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/test/java/org/xcolab/util/html/HtmlUtilTest.java#L7)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> 
> public class HtmlUtilTest {
> ```

Great tests! Another test case that could be interesting is an URL with query strings (both ? and &).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/19)*

**Comment by umov** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[microservices/util/xcolab-utils/pom.xml, line 122 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuRDZe7otcFYx12iqv:-KsxnwDZW_kgET1DRzWG:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/pom.xml#L122)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

You can omit the version here - it's inherited from the `dependencyManagement` tag in the root `pom.xml`.
</blockquote></details>

Done.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuUP6HRFul9OE_2mIz:-Ksxp6GwhU-mGAhDxawa:b-18eeb7) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L25)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

I think if you parse an anchor tag that contains a link within a nested html tag, this regex might not match the second URL since the opening `<` of the nested html tag would fail the regex (this could be solved by using a wildcard with a greedy quantifier, something like `<a[^>]*>.*?</a>`).

This could also be a nice edge case for unit tests:
```html
<a href="www.google.com"><b>www.google.com</b></a>
```

</blockquote></details>

Nice find! Done.
The best would probably be to take an HTML parser. Regex is not really suited for working with HTML.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 100 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuSdBMLrdAC5CjBbCe:-KsxrETGLUgj8rh-UXOt:b-cpmrj8) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L100)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

I'm not sure how it's designed, but it seems like this could potentially be extracted into a `static final` field (if the `LinkExtractor` class is thread-safe or immutable).
</blockquote></details>

Done.
I've checked, it's thread-safe.

---

*[microservices/util/xcolab-utils/src/test/java/org/xcolab/util/html/HtmlUtilTest.java, line 7 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuS-O6lwx0ot_9IidQ:-Ksxqi7D8tDp8q3FwcBP:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/test/java/org/xcolab/util/html/HtmlUtilTest.java#L7)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

Great tests! Another test case that could be interesting is an URL with query strings (both ? and &).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/19)*

**Comment by jobachh** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuUP6HRFul9OE_2mIz:-KsyRaTTaudVX4n7X_Vp:b-ax2pmk) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L25)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

Nice find! Done.
The best would probably be to take an HTML parser. Regex is not really suited for working with HTML.
</blockquote></details>

Generally that's true, but I think our use-case is simple enough for the regex to cover all cases. Anchor tags can't be nested and image tags are empty, so we avoid the problem of matching starting and closing tags. Can you think of a scenario where this regex would fail?

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 100 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuSdBMLrdAC5CjBbCe:-KsySWb9b-X-Sk4S8_CD:b4rr873) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L100)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

Done.
I've checked, it's thread-safe.
</blockquote></details>

That's great, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/19)*

**Comment by umov** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/19#-KsuUP6HRFul9OE_2mIz:-KsyyIimq-9zrOXzhRh3:b-utcbvr) ([raw file](https://github.com/cci-mit/xcolab/blob/7489fea13a2dd3b05436e4ac9192ab68b1627689/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java#L25)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

Generally that's true, but I think our use-case is simple enough for the regex to cover all cases. Anchor tags can't be nested and image tags are empty, so we avoid the problem of matching starting and closing tags. Can you think of a scenario where this regex would fail?
</blockquote></details>

I was speaking generally. I agree that here it should work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/19)*

**Pull request merged**
