### PR TITLE
[COLAB-2411] Add impact adaptation table

### PR DESCRIPTION
**Pull request by jobachhu**
This PR creates a new tab to record impact assessments for adaptation contests. These values are stored in the existing UnversionedProposalAttributes, which are already used for impact comments.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/68)

### CODE REVIEW

**Comment by umov** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java, line 39 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywN_OM1CGM5XvTwKo3:-KyuuxwdZDpae-wukGhW:biwvyop) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java#L39)):*
> ```Java
> 
>     public String getAttributeName() {
>         return "IMPACT_" + name();
> ```

Why is this necessary?

---

*[view/src/main/java/org/xcolab/view/pages/proposals/tabs/access/AdaptationImpactAccessAlgorithm.java, line 27 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywRgYTDy2wNZv21lmE:-KywRgYTDy2wNZv21lmF:b-isnm5b) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/tabs/access/AdaptationImpactAccessAlgorithm.java#L27)):*
> ```Java
> 
>             // this feature was only introduced in the 2017 contest cycle
>             if (contest.getContestYear() < 2017) {
> ```

This should not be a magic number. Declare is statically at the top or move it to some settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68)*

**Comment by jobachhu** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java, line 39 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywN_OM1CGM5XvTwKo3:-KywWEAM2mvTh3bXNfKC:bmcnzwk) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java#L39)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

This is mainly for consistency with the other impact-related attributes (`IMPACT_AUTHOR_COMMENT` and `IMPACT_IAF_COMMENT`) and it allows makes it easier to tell where the attributes came from and distinguish them from non-impact-related attributes in the future.

If we keep the prefix, do you think it would be better to move it as a constant to `AdaptationService.AttributeHelper`, which is where the final attribute name is constructed? Right now the attribute name is determined like this:
```java
category.getAttributeName() + "_" + valueType
```
But maybe something like this makes more sense:
```java
final String ATTRIBUTE_PREFIX = "IMPACT";
return String.join("_", ATTRIBUTE_PREFIX, category.name(), valueType);
```

What do you think?

---

*[view/src/main/java/org/xcolab/view/pages/proposals/tabs/access/AdaptationImpactAccessAlgorithm.java, line 27 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywRgYTDy2wNZv21lmE:-KywVmLxF9unMFxRsuQP:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/tabs/access/AdaptationImpactAccessAlgorithm.java#L27)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

This should not be a magic number. Declare is statically at the top or move it to some settings.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68)*

**Comment by umov** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java, line 39 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywN_OM1CGM5XvTwKo3:-KywZqCvUxEs566UfvHK:ba9u24) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java#L39)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This is mainly for consistency with the other impact-related attributes (`IMPACT_AUTHOR_COMMENT` and `IMPACT_IAF_COMMENT`) and it allows makes it easier to tell where the attributes came from and distinguish them from non-impact-related attributes in the future.

If we keep the prefix, do you think it would be better to move it as a constant to `AdaptationService.AttributeHelper`, which is where the final attribute name is constructed? Right now the attribute name is determined like this:
```java
category.getAttributeName() + "_" + valueType
```
But maybe something like this makes more sense:
```java
final String ATTRIBUTE_PREFIX = "IMPACT";
return String.join("_", ATTRIBUTE_PREFIX, category.name(), valueType);
```

What do you think?
</blockquote></details>

Why don't you just name them with `IMPACT_` then? (like `IMPACT_ECONOMIC_DAMAGES`) And have `getAttributeName` just return the name?
I find that solution with the `ATTRIBUTE_PREFIX` to be overly complicated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68)*

**Comment by jobachhu** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java, line 39 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-KywN_OM1CGM5XvTwKo3:-Kywavtrwbk21ItO8Qdd:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/6fa314c661c0e51c0d067e652953e17093be49fd/view/src/main/java/org/xcolab/view/pages/proposals/impact/adaptation/AdaptationCategory.java#L39)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

Why don't you just name them with `IMPACT_` then? (like `IMPACT_ECONOMIC_DAMAGES`) And have `getAttributeName` just return the name?
I find that solution with the `ATTRIBUTE_PREFIX` to be overly complicated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68)*

**Comment by umov** [comment]
:lgtm:

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68#-:-KywbBBqHHEXJ-nRYc4k:bnfp4nl)*

**Comment by umov** [comment]
Reviewed 14 of 19 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/68)*

**Pull request merged**
