### PR TITLE
[COLAB-2334] Improved client API

### PR DESCRIPTION
**Pull request by jobachhu**
This PR refactors the client API to communicate with out microservices. The existing API attempts to abstract the communication with a RESTful service by providing type-safe methods to build queries against an API with predefined service endpoints and resources. This PR modifies this abstraction by improving the class hierarchy between the classes and reducing the coupling between lightly related classes.

Specifically, it removes the RestService class and its sub-class, this this class combined two concepts: a service (represented by the CoLab service class) and a namespace. I extracted the CoLab service to be independent of the namespace and deferred the resolution of the namespace to the creating of the specific resource. I also changed resources to be represented by Enums to reduce the use of hard-coded string endpoints (especially important when resources are re-used).

Note: this PR will facilitate a simplification of nested rest endpoints in COLAB-2355.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/52)

### CODE REVIEW

**Comment by jobachhu** [comment]
For the review, here's a highlight of the interesting files to review.

These classes are interesting in relation to the restructuring of the class hierarchy:
`org.xcolab.util.http.client.CoLabService`
`org.xcolab.util.http.client.enums.ResourceEnum`
`org.xcolab.util.http.client.enums.ServiceNamespace*`
`org.xcolab.util.http.client.interfaces.AbstractRestResource`
`org.xcolab.util.http.client.RestResource1`

Then as an example of the mass changes, you can review a client:
`org.xcolab.client.contest.resources.ProposalResource`
`org.xcolab.client.proposals.MembershipClient`

**Comment by carlosbpf** [comment]
Reviewed 227 of 227 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java, line 5 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/52#-Kx6xwTBJVEnC8JfYCg0:-Kx6xwTBJVEnC8JfYCg1:b-o7kibg) ([raw file](https://github.com/cci-mit/xcolab/blob/bdba428481c6996301b90cc7d4a2bfd3d358773c/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java#L5)):*
> ```Java
> import org.xcolab.util.http.client.QueryId;
> 
> public interface IdentifiableHttpResource<ResourceT, IdT> extends HttpResource {
> ```

The name Identifiable, is it because it is a named resource? Should we support an nonIdentifiable resource in the future?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/52)*

**Comment by jobachhu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java, line 5 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/52#-Kx6xwTBJVEnC8JfYCg0:-Kx7Sx-ClqXtyJ0pykDu:b-rkxusu) ([raw file](https://github.com/cci-mit/xcolab/blob/bdba428481c6996301b90cc7d4a2bfd3d358773c/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java#L5)):*
<details><summary><i>Previously, carlosbpf (Carlos Paula) wrote…</i></summary><blockquote>

The name Identifiable, is it because it is a named resource? Should we support an nonIdentifiable resource in the future?
</blockquote></details>

The "Identifiable" comes from the fact that this resource has to have an ID. The counter part is the ServiceResource, which does not need to have an ID. This distinctions is needed to allow nested resources, which `RestResource`s support but `ServiceResource`s don't.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/52)*

**Comment by carlosbpf** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java, line 5 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/52#-Kx6xwTBJVEnC8JfYCg0:-KxHmfgZWetLxHofY_AU:b-rgvmpc) ([raw file](https://github.com/cci-mit/xcolab/blob/bdba428481c6996301b90cc7d4a2bfd3d358773c/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/interfaces/IdentifiableHttpResource.java#L5)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

The "Identifiable" comes from the fact that this resource has to have an ID. The counter part is the ServiceResource, which does not need to have an ID. This distinctions is needed to allow nested resources, which `RestResource`s support but `ServiceResource`s don't.
</blockquote></details>

Ah nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/52)*

**Comment by carlosbpf** [comment]
Reviewed 2 of 227 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/52)*

**Pull request merged**
