### PR TITLE
[COLAB-2192] Add CSRF tokens to all forms/requests

### PR DESCRIPTION
**Pull request by umov**
Reactivated CSRF support in Spring Security.
Manually added CSRF tokens to all non `<form:form>`-type forms.
Added CSRF to all AJAX calls by including an `$.ajaxSetup` method call in the root layout `layout.tagx` that adds the CSRF token to the request header of each AJAX calls. The CSRF token for that is shipped with each HTML page in the meta tag `_csrf`.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/22)

### CODE REVIEW

**Comment by jobachh** [comment]
Thanks! One general thought I had is whether we could remove all the inputs for regular forms if we switched those forms to use the `form` element from Spring's taglib. That would look cleaner (if it works).

---

Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[view/src/main/resources/static/js/proposals/discussionComments.js, line 30 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-Ksu_DvJskWd5c2BTdJx:-Ksu_DvJskWd5c2BTdJy:b-sdic6h) ([raw file](https://github.com/cci-mit/xcolab/blob/940961b7b52dabf891eabe9e07b1c431d18a3b24/view/src/main/resources/static/js/proposals/discussionComments.js#L30)):*
> ```JavaScript
>     var formContent = '<form method="post" action="' + url + '">';
>     formContent += '<textarea class="rte-editorPlaceholder" id="text_' + messageId + '" name="comment" style="width: 100%; height: 150px;"></textarea>';
>     formContent += '<input name="_csrf" type="hidden" value="' + $('#_csrf').val() + '"/>';
> ```

I didn't see an element with the id `_csrf` - did you mean to use `$("meta[name='_csrf']").attr("content")` from `layout.tagx`?

Also - theoretically the name of the parameter is customizable, so it might be safer to add another meta tag for that and use that value in the name field.

---

*[view/src/main/webapp/WEB-INF/tags/layout.tagx, line 176 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-Ksu_gfKunCYOjk3traE:-KsuYTtyTMBuxuKyphSN:b-o2ujf4) ([raw file](https://github.com/cci-mit/xcolab/blob/940961b7b52dabf891eabe9e07b1c431d18a3b24/view/src/main/webapp/WEB-INF/tags/layout.tagx#L176)):*
> ```
>                 xhr.setRequestHeader(header, token);
>             }
>         })
> ```

Great solution!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-:-Ksu_AFHYl7tEEWfsRd6:b-y8z3r0)*

**Comment by umov** [comment]
I wanted to do exactly that, initially. However, the problem with that is that with the change of inputs to `form:input`s, we need to set the `path` attribute for data binding. That means that we potentially have to change the controller so that it works correctly with the data binding. While that would be nice and clean, it's a giant task to go through all of our controllers and change them and would not really give us any real benefit. So I've decided it's out of scope for this ticket.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/resources/static/js/proposals/discussionComments.js, line 30 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-Ksu_DvJskWd5c2BTdJx:-KsxsPaADXUw5Qd5m7iv:b-iuqwgs) ([raw file](https://github.com/cci-mit/xcolab/blob/940961b7b52dabf891eabe9e07b1c431d18a3b24/view/src/main/resources/static/js/proposals/discussionComments.js#L30)):*
<details><summary><i>Previously, jobachh (Johannes Bachhuber) wrote…</i></summary><blockquote>

I didn't see an element with the id `_csrf` - did you mean to use `$("meta[name='_csrf']").attr("content")` from `layout.tagx`?

Also - theoretically the name of the parameter is customizable, so it might be safer to add another meta tag for that and use that value in the name field.
</blockquote></details>

No, the `#_csrf` was on purpose.
The corresponding element can be found in `view/src/main/webapp/WEB-INF/tags/collab/discussion/comments.tagx`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-:-Ksxr_ARZLRhw-a7ExXE:b-2zyru0)*

**Comment by umov** [comment]
Added CSRF tokens to MVC tests. Ready for review! @jobachh

**Comment by jobachh** [comment]
Ok, thanks for the explanation. That's too bad that we can't do that, but you're right - reworking all the controllers for all non-spring forms would be out of scope. All good then :+1: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/resources/static/js/proposals/discussionComments.js, line 30 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-Ksu_DvJskWd5c2BTdJx:-KsyYOpbJx695pF482-R:b-ujass3) ([raw file](https://github.com/cci-mit/xcolab/blob/940961b7b52dabf891eabe9e07b1c431d18a3b24/view/src/main/resources/static/js/proposals/discussionComments.js#L30)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

No, the `#_csrf` was on purpose.
The corresponding element can be found in `view/src/main/webapp/WEB-INF/tags/collab/discussion/comments.tagx`
</blockquote></details>

Ah right, I missed that. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/22#-:-KsyYpc_jiVeZAAEOtHp:b-n2wren)*

**Pull request merged**
