### PR TITLE
[COLAB-2379] Refactor proposal sorting

### PR DESCRIPTION
**Pull request by jobachhu**
This PR simplifies the `ProposalsSortFilterBean` (now `SortedProposalList`) class, which did not need to be mutable and had some duplicate code (the comparator was initialized twice, overwriting the first initialization).

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/57)

### CODE REVIEW

**Comment by umov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/wrappers/SortedProposalList.java, line 29 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/57#-Kx9kyNsRhOcdgWm7hNV:-Kx9kyNsRhOcdgWm7hNW:b-4vcvjf) ([raw file](https://github.com/cci-mit/xcolab/blob/5549ead24f8befc058f14616997e72d0d23a5d54/view/src/main/java/org/xcolab/view/pages/proposals/wrappers/SortedProposalList.java#L29)):*
> ```Java
> 
>     private void initProposalLists(List<Proposal> proposals) {
>         for (Proposal contest : proposals) {
> ```

Why is this variable named `contest`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/57)*

**Comment by umov** [comment]
@jobachhu Not necessarily an issue, but do you know why Codacy is unhappy?

**Comment by jobachhu** [comment]
@umov Looks like there's a little display bug with codacy that's hiding the issue, but it seems to be complaining about the [NPath complexity of the `sortProposalLists`](https://www.codacy.com/app/MIT-CCI/XCoLab/file/11372073304/issues/source?fileBranchId=5615221) method.

**Comment by jobachhu** [comment]
I extracted a method from the `sortProposalList` method to reduce complexity - that should satisfy codacy.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/wrappers/SortedProposalList.java, line 29 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/57#-Kx9kyNsRhOcdgWm7hNV:-KxAB6Z367V4Qct-F_hD:bzsyvr) ([raw file](https://github.com/cci-mit/xcolab/blob/5549ead24f8befc058f14616997e72d0d23a5d54/view/src/main/java/org/xcolab/view/pages/proposals/wrappers/SortedProposalList.java#L29)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

Why is this variable named `contest`?
</blockquote></details>

Good catch, I didn't see that. Renamed to `proposal`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/57#-:-KxABDAT4SdfUFQ8cEMR:b-hkzokw)*

**Comment by umov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/57#-:-KxE0V53eOk6P8fiYDEj:bnfp4nl)*

**Pull request merged**
