### PR TITLE
[COLAB-2236] error handling batch registration

### PR DESCRIPTION
**Pull request by cwoebker**
Error handling for batch registration. Only register everyone if there is no error.
Right now I use a hack to get rid of a weird error. Let's discuss in the code.

Other parts of the code are still work in progress.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/115)

### CODE REVIEW

**Comment by cwoebker** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 251 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L47qXLm9UjANVqYkHis:-L47qXLm9UjANVqYkHit:byqjeab) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L251)):*
> ```Java
>     @PostMapping("tab/ADMIN/batchRegister")
>     public String batchRegisterMembers(HttpServletRequest request, HttpServletResponse response,
>             BatchRegisterBean batchRegisterBean, VotingReportBean votingReportBean, ProposalReportBean proposalReportBean) throws IOException {
> ```

This is the hack I mentioned. I have to add a dummy VotingReportBean and a dummy ProposalReportBean to get rd of the error. I don't quite understand why these matter in the first place for my batchRegister function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by jobachhu** [comment]
Good work! I know the rest of the code is still WIP - I still left some other comments 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 251 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L47qXLm9UjANVqYkHis:-L4BklcdLtmjWBEAA1Rb:b-8azpdl) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L251)):*
<details><summary><i>Previously, cwoebker (Cecil Woebker) wrote…</i></summary><blockquote>

This is the hack I mentioned. I have to add a dummy VotingReportBean and a dummy ProposalReportBean to get rd of the error. I don't quite understand why these matter in the first place for my batchRegister function.
</blockquote></details>

Ah I see! You can remove the parameters again, I realized what's going on now. When retuning the `TAB_NAME`, spring will render that page so it will need its model to be populated with all variables. I just committed a fix to your branch that will make sure the beans exist whenever `adminTab.jspx` is rendered. You can do that by adding a `jsp:useBean` tag in the jspx file. This tag will create the bean using the default constructor if it doesn't already exist in the model.

The reason adding the parameters fixed this issues is because whenever you have a bean parameter, and no such bean was submitted, spring will automatically initialize it using the default constructor. That bean is then added to the model, which is why there is no error during page rendering.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 255 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BahVyHaqXmuEOcmbW:-L4BahVyHaqXmuEOcmbX:bthy9oi) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L255)):*
> ```Java
>             ErrorText.ACCESS_DENIED.flashAndRedirect(request, response);
>             return;
>         }*/
> ```

You can slightly change the pattern to return the view directly: `return ErrorText.ACCESS_DENIED.flashAndReturnView(request);`

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 272 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BeaK_AtTUO0g7-85M:-L4BeaK_AtTUO0g7-85N:b-dcbfvu) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L272)):*
> ```Java
>             java.util.regex.Matcher m = p.matcher(email);
>             if (!m.matches()) {
>                 AlertMessage.danger("Batch registration: Invalid email address.").flash(request);
> ```

This validation already happens in the background ("magic) thanks to the `@Email` annotation in the bean. You just need to do a few things to make it work:
1. Add the `@Valid` annotation in front of the BatchRegisterBean parameter: `@Valid BatchRegisterBean batchRegisterBean`
2. Add a new parameter `BindingResult result` **after** the bean parameter
3. Return the view when there's an error:
```java
if (result.hasErrors()) {
    AlertMessage.danger("Batch registration failed. Make sure there are no errors in your input.").flash(request);
    return TAB_VIEW;
}
```
Note that sometimes the view won't render without setting a few model parameters, you might have to set them before returning.

You can retrieve these errors in the view using ` <form:errors cssClass="c-Alert c-Alert__error" path="countryCode" />`

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 16 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bcueghox366vZ_wY4:-L4Bcueghox366vZ_wY5:bbz3wyh) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L16)):*
> ```
>     
> 
>     
> ```

The variable is called `batchRegisterBean` not `registerBatchBean`. You probably won't need this declaration anyways after you remove the value attributes below (see other comments below).

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 197 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BcU-vtSY5b8buPJ0K:-L4BcU-vtSY5b8buPJ0L:b-3zef6) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L197)):*
> ```
>             <form:form action="/admin/contest/manager/tab/ADMIN/batchRegister" commandName="batchRegisterBean"
>                        id="batchRegisterForm" method="post">
>                 <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
> ```

One cool thing about the spring forms is that they actually insert the hidden input with the CSRF token for us :) You can delete this line.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 204 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BjYdgFs1pbVpFEoHD:-L4BjYdgFs1pbVpFEoHE:b-5grqhc) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L204)):*
> ```
>                 </div>
>                 <div>
>                     <form:textarea id="batchRegisterMembersList" name="batchText" class="form-control" path="batchText"
> ```

You can drop the `name` attribute - spring will populate that automatically (with the path)

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 205 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bbhw2HJv88j9p2RUc:-L4Bbhw3-XWAQrKEeIPx:b-xmhdn5) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L205)):*
> ```
>                 <div>
>                     <form:textarea id="batchRegisterMembersList" name="batchText" class="form-control" path="batchText"
>                                style="width: 100%;" value="${batchRegisterBean.batchText}" />
> ```

You don't need the `value` attribute - spring will automatically use the value found in the path.

The binding works both ways: when the page loads, the fields use the values from the bean and when it's submitted, the bean is populated with the values from the inputs.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 209 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bc3TpiPxcdPGqggL4:-L4Bc3Tqi5yD5EnHwIPx:beog8m0) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L209)):*
> ```
>                 <div class="form-check">
>                     
>                     <form:checkbox name="asGuests" path="asGuests" class="form-check-input" id="asGuests"
> ```

The spring form thats have a slightly strange format to specify class names because they are backed by a Java class and the word `class` is a reserved keyword in Java. Use `cssClass=""` instead of `class=""` when using a `form:*` tag.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 210 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BbpIAsWSmPZnFhW2x:-L4BbpIAsWSmPZnFhW2y:bkt7eog) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L210)):*
> ```
>                     
>                     <form:checkbox name="asGuests" path="asGuests" class="form-check-input" id="asGuests"
>                            style="float: none; height: initial;" value="${batchRegisterBean.asGuests}"/>
> ```

Same here, you don't need the value attribute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-:-L4Be30OWXpDkDje4qkR:bym25nj)*

**Comment by cwoebker** [comment]
Review status: 1 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 251 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L47qXLm9UjANVqYkHis:-L4HHIHu0O4pSQVpqSot:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L251)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Ah I see! You can remove the parameters again, I realized what's going on now. When retuning the `TAB_NAME`, spring will render that page so it will need its model to be populated with all variables. I just committed a fix to your branch that will make sure the beans exist whenever `adminTab.jspx` is rendered. You can do that by adding a `jsp:useBean` tag in the jspx file. This tag will create the bean using the default constructor if it doesn't already exist in the model.

The reason adding the parameters fixed this issues is because whenever you have a bean parameter, and no such bean was submitted, spring will automatically initialize it using the default constructor. That bean is then added to the model, which is why there is no error during page rendering.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 255 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BahVyHaqXmuEOcmbW:-L4HHQgTpRftB5p0M86H:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L255)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

You can slightly change the pattern to return the view directly: `return ErrorText.ACCESS_DENIED.flashAndReturnView(request);`
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 16 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bcueghox366vZ_wY4:-L4HHFNMmzhhYiFXCxG9:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L16)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

The variable is called `batchRegisterBean` not `registerBatchBean`. You probably won't need this declaration anyways after you remove the value attributes below (see other comments below).
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 197 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BcU-vtSY5b8buPJ0K:-L4HHEfwcNLfkoS6F2Ub:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L197)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

One cool thing about the spring forms is that they actually insert the hidden input with the CSRF token for us :) You can delete this line.
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 204 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BjYdgFs1pbVpFEoHD:-L4HHDzqKt4U6AvzuJTR:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L204)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

You can drop the `name` attribute - spring will populate that automatically (with the path)
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 205 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bbhw2HJv88j9p2RUc:-L4HHDDpVIQ-rBohnxUv:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L205)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

You don't need the `value` attribute - spring will automatically use the value found in the path.

The binding works both ways: when the page loads, the fields use the values from the bean and when it's submitted, the bean is populated with the values from the inputs.
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 209 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4Bc3TpiPxcdPGqggL4:-L4HHCo4ckLV_svJhKCu:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L209)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

The spring form thats have a slightly strange format to specify class names because they are backed by a Java class and the word `class` is a reserved keyword in Java. Use `cssClass=""` instead of `class=""` when using a `form:*` tag.
</blockquote></details>

Done.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx, line 210 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BbpIAsWSmPZnFhW2x:-L4HHCALtCTiKUwhyFW_:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx#L210)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Same here, you don't need the value attribute.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by cwoebker** [comment]
Review status: 1 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 272 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BeaK_AtTUO0g7-85M:-L4HI87uBYlX2K9ZuI8V:bibg603) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L272)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This validation already happens in the background ("magic) thanks to the `@Email` annotation in the bean. You just need to do a few things to make it work:
1. Add the `@Valid` annotation in front of the BatchRegisterBean parameter: `@Valid BatchRegisterBean batchRegisterBean`
2. Add a new parameter `BindingResult result` **after** the bean parameter
3. Return the view when there's an error:
```java
if (result.hasErrors()) {
    AlertMessage.danger("Batch registration failed. Make sure there are no errors in your input.").flash(request);
    return TAB_VIEW;
}
```
Note that sometimes the view won't render without setting a few model parameters, you might have to set them before returning.

You can retrieve these errors in the view using ` <form:errors cssClass="c-Alert c-Alert__error" path="countryCode" />`
</blockquote></details>

The problem I see here is that, as of now, we just use a large string to store all the data in the form... is there a way to apply these validators to part of the text input after the fact? The Email, firstName, lastName variables from the Bean aren't really used right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by jobachhu** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 272 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BeaK_AtTUO0g7-85M:-L4WsEFreylHwhKZLnBS:b-g8oeuo) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L272)):*
<details><summary><i>Previously, cwoebker (Cecil Woebker) wrote…</i></summary><blockquote>

The problem I see here is that, as of now, we just use a large string to store all the data in the form... is there a way to apply these validators to part of the text input after the fact? The Email, firstName, lastName variables from the Bean aren't really used right now.
</blockquote></details>

I see, that makes sense. You can still apply the validations by turning each line into a separate bean with these validators and then validating it using a `org.springframework.validation.Validator`object (you can get the `Validator` by injecting it into the controller) and maually calling its validate method.

Other option if you're interested in playing around with this more: we could adapt it to use individual first name/last name/email fields for every user (and use some JavaScripts to add new rows). Then we can use the bean to validate individual fields. We have a similar client-side functionality for the logo widget (check out http://localhost:18082/widgets/logos/preferences).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by cwoebker** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 272 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BeaK_AtTUO0g7-85M:-L4c_nZGLG6nFSNk-JzH:b-n4nz0g) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L272)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

I see, that makes sense. You can still apply the validations by turning each line into a separate bean with these validators and then validating it using a `org.springframework.validation.Validator`object (you can get the `Validator` by injecting it into the controller) and maually calling its validate method.

Other option if you're interested in playing around with this more: we could adapt it to use individual first name/last name/email fields for every user (and use some JavaScripts to add new rows). Then we can use the bean to validate individual fields. We have a similar client-side functionality for the logo widget (check out http://localhost:18082/widgets/logos/preferences).


</blockquote></details>

While I agree that it would be nice to adapt the interface. I think the use case of preparing a larger list of people and then easily copying and pasting that into the web form also holds value. I will go with the first option then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by jobachhu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 272 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L4BeaK_AtTUO0g7-85M:-L4cby7p06ggZkGUPgJY:b-muqjlv) ([raw file](https://github.com/cci-mit/xcolab/blob/95424b3b2b7357dbad581109d5599b577f5618b7/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L272)):*
<details><summary><i>Previously, cwoebker (Cecil Woebker) wrote…</i></summary><blockquote>

While I agree that it would be nice to adapt the interface. I think the use case of preparing a larger list of people and then easily copying and pasting that into the web form also holds value. I will go with the first option then.
</blockquote></details>

Great point about copying lists of people! I agree :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by jobachhu** [comment]
Looking good! Good job, Cecil! Just a few more

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 86 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GKxrK6du-UJ9S5Rxz:-L5GKxrK6du-UJ9S5Ry-:b-bzi7ve) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L86)):*
> ```Java
> 
>     @Autowired
>     Validator validator;
> ```

This should be a `private` field.

We also generally prefer constructor injection to field injection, as it allows making the field `final` and prevents accidentally creating an instance without the field by calling the default constructor. You can just add `Validator validator` as parameter to the constructor, as it already has the `@Autowired` annotation, and then assign it to this field.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 273 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GLXLJJXP1qgf-rllq:-L5GLXLJJXP1qgf-rllr:bwgbj0e) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L273)):*
> ```Java
> 
>             ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
>             Validator validator = factory.getValidator();
> ```

No need to instantiate a new validator - you can use the injected `Validator` field instead

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 293 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GZqRzQMoEAWRbFn38:-L5GZqRzQMoEAWRbFn39:beym9p8) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L293)):*
> ```Java
>         for (String memberString : memberStrings) {
>             final String[] values = memberString.split(";");
>             Member member = loginRegisterService.autoRegister(values[0], values[1], values[2]);
> ```

This is the second time you are splitting the string and then referencing the values by their position in the array. It would be better to re-used named variables here.

I would break this process into 3 steps:
1. convert `memberStrings` into Set of `BatchRegisterLineBean`s
2. validate all beans
3. create user from all beans

For 1 you can use a stream:
```
final Set<BatchRegisterLineBean> registerLineBeans = 
    Arrays.stream(memberStrings)
        .map(memberString -> memberString.split(";"))
        .map(values -> new BatchRegisterLineBean(values[1], values[2], values[0]))
        .collect(Collectors.toSet());
```

Then for 2 and 3 you can loop over this set instead of the strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-:-L5GgSZYLdcu7fKCVeOq:b-t80hk7)*

**Comment by cwoebker** [comment]
Only one last thing is broken. For some reason the checkbox doesn't bind to the bean. Stil working on that one.

---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 86 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GKxrK6du-UJ9S5Rxz:-L5HI4c8OX6Oo3Vo4DW4:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L86)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This should be a `private` field.

We also generally prefer constructor injection to field injection, as it allows making the field `final` and prevents accidentally creating an instance without the field by calling the default constructor. You can just add `Validator validator` as parameter to the constructor, as it already has the `@Autowired` annotation, and then assign it to this field.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 273 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GLXLJJXP1qgf-rllq:-L5HI6dRB3Z2dQiO3BxZ:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L273)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

No need to instantiate a new validator - you can use the injected `Validator` field instead
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 293 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5GZqRzQMoEAWRbFn38:-L5HJ_SD-swGixC1UnDr:b3oh8n) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L293)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This is the second time you are splitting the string and then referencing the values by their position in the array. It would be better to re-used named variables here.

I would break this process into 3 steps:
1. convert `memberStrings` into Set of `BatchRegisterLineBean`s
2. validate all beans
3. create user from all beans

For 1 you can use a stream:
```
final Set<BatchRegisterLineBean> registerLineBeans = 
    Arrays.stream(memberStrings)
        .map(memberString -> memberString.split(";"))
        .map(values -> new BatchRegisterLineBean(values[1], values[2], values[0]))
        .collect(Collectors.toSet());
```

Then for 2 and 3 you can loop over this set instead of the strings.
</blockquote></details>


Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 294 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5HMxc054KRVUFnNctb:-L5HMxc054KRVUFnNctc:busda6j) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L294)):*
> ```Java
>             final String[] values = memberString.split(";");
>             Member member = loginRegisterService.autoRegister(values[0], values[1], values[2]);
>             if (batchRegisterBean.getAsGuests()) {
> ```

This one gives a NullPointer exception right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-:-L5HMqv2yuEg5418_tVj:bp51s3h)*

**Comment by cwoebker** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, line 294 at r4](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-L5HMxc054KRVUFnNctb:-L5nUNwBlNbUToGBouXc:b-xi7b7z) ([raw file](https://github.com/cci-mit/xcolab/blob/9082cc5ad2ba4994b99e0222307fb37f8f6852cb/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java#L294)):*
<details><summary><i>Previously, cwoebker (Cecil Woebker) wrote…</i></summary><blockquote>

This one gives a NullPointer exception right now.
</blockquote></details>

Done. Using "boolean" now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115)*

**Comment by cwoebker** [comment]
@jobachhu null pointer exception is also fixed. Let me know if you want to check the code once more.

**Comment by jobachhu** [comment]
Looks good, thanks Cecil!

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/115#-:-L5pavD3nnPG4RAMkB0L:bupaaaa)*

**Pull request merged**
