### PR TITLE
[COLAB-2355] Simplify nested resources

### PR DESCRIPTION
**Pull request by jobachhu**
This PR simplifies the API for creating nested Rest resources. It does so in two ways:
1. Creating a virtual sub-resource that does not need type information because it is never queried and only used to resolve nested resources. This can have two reasons: using a parent resource in another client instance (in the same service) or using a parent resource in another service (this should be avoided).
2. Creating a shortcut for endpoint that return lists of ids (which are often used in sub-resources)

~Depends on #52.~ Merged

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/60)

### CODE REVIEW

**Comment by umov** [comment]
@jobachhu, as we discussed. This PR is too big to be reviewed as usual. Any ideas on how we should tackle this? Should I just trust you and merge it? Or do you want to point out the most important changes or pieces of code you want me to look over?

**Comment by umov** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java, line 9 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/60#-Ky2hiD2b7EeS5rPGOP_:-Ky2hiD2b7EeS5rPGOPa:bapcl1d) ([raw file](https://github.com/cci-mit/xcolab/blob/33b896f49cd3bc82b6fd9f868dde6bcb503f90f6/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java#L9)):*
> ```Java
> public class TypeProvider<T> {
> 
>     public static final TypeProvider<Long> LONG = new TypeProvider<>(Long.class,
> ```

I find the name `LONG` confusing, because it sounds like it would be a `Long`. I would prefer a name that makes it clear that the type represents a list of Longs. (e.g. `LONG_LIST`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/60)*

**Comment by jobachhu** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java, line 9 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/60#-Ky2hiD2b7EeS5rPGOP_:-Ky2zLJ2Rd9PUJnuKnke:baiy6b7) ([raw file](https://github.com/cci-mit/xcolab/blob/33b896f49cd3bc82b6fd9f868dde6bcb503f90f6/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java#L9)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

I find the name `LONG` confusing, because it sounds like it would be a `Long`. I would prefer a name that makes it clear that the type represents a list of Longs. (e.g. `LONG_LIST`)
</blockquote></details>

Hm the thing is that the type does not directly represent a list of longs. It represents the type information for the `Long` class, which is both the entityType (`Long.class`) and the listType (captured using the `ParameterizedTypeReference`). We could rename it to something like `LONG_TYPE`, but this might be redundant since the constant would be used as the qualified type `TypeProvider.LONG`.

Currently, we only use the resource's list endpoint so we are effectively using it as a list of longs, but it could be used in other ways. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/60)*

**Comment by umov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java, line 9 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/60#-Ky2hiD2b7EeS5rPGOP_:-KyHus_Wo84oVIPm1soJ:b-r9x6ox) ([raw file](https://github.com/cci-mit/xcolab/blob/33b896f49cd3bc82b6fd9f868dde6bcb503f90f6/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/client/types/TypeProvider.java#L9)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Hm the thing is that the type does not directly represent a list of longs. It represents the type information for the `Long` class, which is both the entityType (`Long.class`) and the listType (captured using the `ParameterizedTypeReference`). We could rename it to something like `LONG_TYPE`, but this might be redundant since the constant would be used as the qualified type `TypeProvider.LONG`.

Currently, we only use the resource's list endpoint so we are effectively using it as a list of longs, but it could be used in other ways. What do you think?
</blockquote></details>

Okay, I see.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/60)*

**Comment by umov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/60#-:-KyHv6q5uCtTrj-beUlH:bnfp4nl)*

**Pull request merged**
