### PR TITLE
[COLAB-2307] Platform Wide Teams

### PR DESCRIPTION
**Pull request by umov**
This PR implements platform wide teams. The teams can be set up by admins in the *Teams* tab in the CMS. Users who are in a team can now select that team when creating or editing a proposal. Upon saving, all team members are added to the proposal team and subscribed to the proposal.

Notes:
- The selected team is not really saved in the proposal. Its name is used for the proposal team name and all the members are added, but the actual information that the platform-wide team is the proposal team is lost. We could consider changing that if it becomes necessary.

---
This change is [Reviewable](https://reviewable.io/reviews/cci-mit/xcolab/50)

### CODE REVIEW

**Comment by jobachhu** [comment]
For the current use-case, preserving the team information isn't important but it might be worth looking into in the future. Good call on implementing it like this for now :+1: 

Looks and works great overall - good job!

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks broke.

---

*[microservices/clients/members-client/src/main/java/org/xcolab/client/members/PlatformTeamsClient.java, line 83 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrIsbciQv6k4tqF7wr:-KwrIsbciQv6k4tqF7ws:b-vtrega) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/clients/members-client/src/main/java/org/xcolab/client/members/PlatformTeamsClient.java#L83)):*
> ```Java
>         ServiceRequestUtils.clearCache(CacheName.PLATFORMTEAM);
>         return platformTeamResource
>                 .service(team.getId_(), "members/" + member.getId_(), Boolean.class)
> ```

FYI (no action required): there's a better way to do this with the API, but let's wait until after #52 is merged, as this changed slightly. Generally, the idea is to define these as nested resources.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDao.java, line 18 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJN-QpRirH4hVYKIp:-KwrJN-QpRirH4hVYKIq:b-ies9je) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDao.java#L18)):*
> ```Java
>     int delete(long teamId);
>     int addMember(long teamId, long memberId);
>     int removeMember(long teamId, long memberId);
> ```

Code style: reformat (option + cmd + L) to add lines between methods.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 33 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJZFzh_r3VqpJkw6L:-KwrJZFzh_r3VqpJkw6M:bi2odwp) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L33)):*
> ```Java
>         final SelectQuery<Record> query = dslContext.select(PLATFORM_TEAM.fields())
>                 .from(PLATFORM_TEAM)
>                 .getQuery();
> ```

When you don't add any conditional queries, you can skip the variable assignment (and the `getQuery()` call).

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 53 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJox1iKgIG2CS_tjg:-KwrJox1iKgIG2CS_tjh:b-si2o9j) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L53)):*
> ```Java
>         this.dslContext.insertInto(PLATFORM_TEAM, PLATFORM_TEAM.ID_, PLATFORM_TEAM.NAME)
>                 .values(team.getId_(), team.getName())
>                 .onDuplicateKeyUpdate()
> ```

Nice, this is a cool idea! I would maybe update the method name to reflect that this method creates or updates the entry.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 64 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrK0qQSWudT2W8Jw24:-KwrK0qQSWudT2W8Jw25:b-4aaebx) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L64)):*
> ```Java
>                 .set(PLATFORM_TEAM.NAME, name)
>                 .execute();
>         return getPlatformTeam(this.dslContext.lastID().longValue()).orElse(null);
> ```

I would use a returning query for this to have it all in a single query (MySQL doesn't support returning clauses, but jOOQ will emulate it).

It would be used like this:
```java
final ReportRecord record = dslContext.insertInto(REPORT)
                .set(REPORT.REPORTER_MEMBER_ID, report.getReporterMemberId())
                .returning(REPORT.REPORT_ID)
                .fetchOne();
        if (record != null) {
            report.setReportId(record.getReportId());
            return report;
        }
        return null;
```

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/web/PlatformTeamsController.java, line 26 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrLHWtDqbsahMWbIe_:-KwrLHWtDqbsahMWbIea:b63sy70) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/web/PlatformTeamsController.java#L26)):*
> ```Java
> @RestController
> @RequestMapping("/platformteams")
> public class PlatformTeamsController {
> ```

This class looks great - very clean :+1: 

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/caching/CacheName.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgy_K0szhkZihwJ2TN:-Kwgy_K0szhkZihwJ2TO:b-gzf72n) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/caching/CacheName.java#L25)):*
> ```Java
>     ROLES(100, CacheDuration.MEDIUM),
>     CONTENT(50, CacheDuration.DAILY),
>     PLATFORMTEAM(50, CacheDuration.DAILY);
> ```

Two words should be separated by an underscore (`PLATFORM_TEAM`).

---

*[sql/deployments/deployment-2017-10-16.sql, line 1 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh5dMMjLvZTaTdc2Z8:-Kwh5dMMjLvZTaTdc2Z9:b-ih3re4) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/deployments/deployment-2017-10-16.sql#L1)):*
> ```SQLPL
> CREATE TABLE xcolab.xcolab_PlatformTeam
> ```

The migration script has a database prefix (won't work if database name is different).

---

*[sql/deployments/deployment-2017-10-16.sql, line 13 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh61SSJGvkE4ztSCid:-Kwh61SSJGvkE4ztSCie:b7rqxqs) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/deployments/deployment-2017-10-16.sql#L13)):*
> ```SQLPL
>     CONSTRAINT xcolab_PlatformTeamMember_userId_teamId_pk PRIMARY KEY (userId, teamId),
>     CONSTRAINT xcolab_PlatformTeamMember_members_Member_id__fk FOREIGN KEY (userId) REFERENCES members_Member (id_) ON DELETE CASCADE ON UPDATE CASCADE,
>     CONSTRAINT xcolab_PlatformTeamMember_xcolab_PlatformTeam_id__fk FOREIGN KEY (teamId) REFERENCES xcolab_PlatformTeam (id_) ON DELETE CASCADE ON UPDATE CASCADE
> ```

I got this when running the script (on `mysql  Ver 15.1 Distrib 10.0.32-MariaDB`):

```
MariaDB [riskdev]> CREATE TABLE xcolab_PlatformTeamMember
    -> (
    ->     userId BIGINT(20) NOT NULL,
    ->     teamId BIGINT(20) NOT NULL,
    ->     CONSTRAINT xcolab_PlatformTeamMember_userId_teamId_pk PRIMARY KEY (userId, teamId),
    ->     CONSTRAINT xcolab_PlatformTeamMember_members_Member_id__fk FOREIGN KEY (userId) REFERENCES members_Member (id_) ON DELETE CASCADE ON UPDATE CASCADE,
    ->     CONSTRAINT xcolab_PlatformTeamMember_xcolab_PlatformTeam_id__fk FOREIGN KEY (teamId) REFERENCES xcolab_PlatformTeam (id_) ON DELETE CASCADE ON UPDATE CASCADE
    -> );
ERROR 1005 (HY000): Can't create table `riskdev`.`xcolab_PlatformTeamMember` (errno: 150 "Foreign key constraint is incorrectly formed")
```

---

*[sql/starter/xcolab-schema.sql, line 1248 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgz5xkdbburNKfuDDh:-Kwgz5xkdbburNKfuDDi:bjwizzi) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/starter/xcolab-schema.sql#L1248)):*
> ```SQLPL
>     `name` VARCHAR(256) DEFAULT NULL,
>     PRIMARY KEY (`id_`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;;
> ```

There are two terminating semi-colons here.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java, line 127 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrM95h1cOQvNHFtAYT:-KwrM95h1cOQvNHFtAYU:bownabm) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java#L127)):*
> ```Java
> 
>         if (!tabWrapper.getCanEdit()) {
>             response.sendRedirect(ContestManagerTabs.TEAMS.getTabUrl(teamId));
> ```

I know this is probably copied from another tab that has the same behavior, but the "new" way of doing this is to have the handlers always return `String` and then do one of two things:
1) return `return new AccessDeniedPage(member).toViewName(response);` in case of permission error
2) return `"redirect:" + redirectUrl` if you want to redirect somewhere

After that, you can also remove the `IOException` from the throws clause above. Same applies to the other handlers.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java, line 186 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrLbtBD2gyn-afhMjP:-KwrLbtBD2gyn-afhMjQ:bf60ajz) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java#L186)):*
> ```Java
>     }
> 
>     private org.xcolab.client.members.pojo.PlatformTeam addNewTeam() {
> ```

`PlatformTeam` should be imported.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/requests/UpdateProposalDetailsBean.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrNC74P6enzk4Td6pm:-KwrNC74P6enzk4Td6pn:b-k9db0m) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/requests/UpdateProposalDetailsBean.java#L25)):*
> ```Java
>     @Length(max = 20, message = "The team name is limited to 20 characters.")
>     private String team;
>     private Long chooseTeam;
> ```

The variable name sounds like a prompt, I think `chosenTeam` or `selectedTeam` would be more appropriate.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java, line 221 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh--xzSXKLuY5VG-T-:-Kwh--xzSXKLuY5VG-T0:bf3z8aw) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java#L221)):*
> ```Java
>                 // Set team name
>                 updateProposalSectionsBean.setTeam(team.getName());
>             } catch (EntityNotFoundException ignored) {}
> ```

Why do we ignore this exception? It would also be better for the client methods to throw specific exceptions and to catch those separately.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java, line 3 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwgzsZOrWsOA49UjYjx:-KwgzsZOrWsOA49UjYjy:bry1twe) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java#L3)):*
> ```Java
> package org.xcolab.view.pages.proposals.view.proposal;
> 
> import javafx.application.Platform;
> ```

Looks like an accidental import.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java, line 143 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgzn4BlXoEC45d_DHz:-Kwgzn4BlXoEC45d_DI-:bdk7ku9) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java#L143)):*
> ```Java
>         model.addAttribute("saveUrl", contest.getNewProposalLinkUrl());
>         List<PlatformTeam> teams = new ArrayList<>(PlatformTeamsClient.getTeams(loggedInMember));
>         teams.add(0, new PlatformTeam());
> ```

Why is this needed?

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalDescriptionTabController.java, line 164 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgzg1qx7_JCAlTZui6:-Kwgzg1qx7_JCAlTZui7:b2nibe8) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalDescriptionTabController.java#L164)):*
> ```Java
>                     ConfigurationAttributeKey.PROPOSALS_PICKER_DEFAULT_TAB_CONTESTS.get());
>             List<PlatformTeam> teams = new ArrayList<>(PlatformTeamsClient.getTeams(currentMember));
>             teams.add(0, new PlatformTeam());
> ```

(same as above - why do we need this?)

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/teamsTab.jspx, line 9 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrNctofdf3ioY6wanX:-KwrNctofdf3ioY6wanY:b-xkxfn5) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/teamsTab.jspx#L9)):*
> ```
> <xcolab:layout>
>     
>     
> ```

This looks unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-:-Kwh-g4kgDozBiHGM15g:b-mpdebl)*

**Comment by umov** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDao.java, line 18 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJN-QpRirH4hVYKIp:-KwvG7TVyW6m3GBReCCA:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDao.java#L18)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Code style: reformat (option + cmd + L) to add lines between methods.
</blockquote></details>

Done.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 33 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJZFzh_r3VqpJkw6L:-KwvGL_B0uDM-HKHrhth:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L33)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

When you don't add any conditional queries, you can skip the variable assignment (and the `getQuery()` call).
</blockquote></details>

Done.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 53 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrJox1iKgIG2CS_tjg:-KwvGUxXhSosYnOb0roe:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L53)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Nice, this is a cool idea! I would maybe update the method name to reflect that this method creates or updates the entry.
</blockquote></details>

Done.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java, line 64 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrK0qQSWudT2W8Jw24:-KwvHkdmWhG-8BrPLYGk:b6e52hh) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/platformteam/PlatformTeamDaoImpl.java#L64)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

I would use a returning query for this to have it all in a single query (MySQL doesn't support returning clauses, but jOOQ will emulate it).

It would be used like this:
```java
final ReportRecord record = dslContext.insertInto(REPORT)
                .set(REPORT.REPORTER_MEMBER_ID, report.getReporterMemberId())
                .returning(REPORT.REPORT_ID)
                .fetchOne();
        if (record != null) {
            report.setReportId(record.getReportId());
            return report;
        }
        return null;
```
</blockquote></details>

Done.

Doesn't really work like that because we don't have the PlatformTeam object here. But to a new query, I'm now creating the object in the code.

---

*[microservices/services/members-service/src/main/java/org/xcolab/service/members/web/PlatformTeamsController.java, line 26 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrLHWtDqbsahMWbIe_:-KwvdhqTIe_FvDiyz-38:b32w0x) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/services/members-service/src/main/java/org/xcolab/service/members/web/PlatformTeamsController.java#L26)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This class looks great - very clean :+1: 
</blockquote></details>

OK

---

*[microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/caching/CacheName.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgy_K0szhkZihwJ2TN:-KwvI6YJvV8hVZ4vN8-b:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/microservices/util/xcolab-utils/src/main/java/org/xcolab/util/http/caching/CacheName.java#L25)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Two words should be separated by an underscore (`PLATFORM_TEAM`).
</blockquote></details>

Done.

---

*[sql/deployments/deployment-2017-10-16.sql, line 1 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh5dMMjLvZTaTdc2Z8:-KwvInlylcH1P0Gl3pi7:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/deployments/deployment-2017-10-16.sql#L1)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

The migration script has a database prefix (won't work if database name is different).
</blockquote></details>

Done.

---

*[sql/deployments/deployment-2017-10-16.sql, line 13 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh61SSJGvkE4ztSCid:-KwvN4EqJSmQZ1DcOapG:bw08ebd) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/deployments/deployment-2017-10-16.sql#L13)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

I got this when running the script (on `mysql  Ver 15.1 Distrib 10.0.32-MariaDB`):

```
MariaDB [riskdev]> CREATE TABLE xcolab_PlatformTeamMember
    -> (
    ->     userId BIGINT(20) NOT NULL,
    ->     teamId BIGINT(20) NOT NULL,
    ->     CONSTRAINT xcolab_PlatformTeamMember_userId_teamId_pk PRIMARY KEY (userId, teamId),
    ->     CONSTRAINT xcolab_PlatformTeamMember_members_Member_id__fk FOREIGN KEY (userId) REFERENCES members_Member (id_) ON DELETE CASCADE ON UPDATE CASCADE,
    ->     CONSTRAINT xcolab_PlatformTeamMember_xcolab_PlatformTeam_id__fk FOREIGN KEY (teamId) REFERENCES xcolab_PlatformTeam (id_) ON DELETE CASCADE ON UPDATE CASCADE
    -> );
ERROR 1005 (HY000): Can't create table `riskdev`.`xcolab_PlatformTeamMember` (errno: 150 "Foreign key constraint is incorrectly formed")
```
</blockquote></details>

Fixed. Problem was that `members_Member` hat `ENGINE=MyISAM`. I've added `ALTER TABLE members_Member ENGINE=InnoDB;` to the deployment script.

---

*[sql/starter/xcolab-schema.sql, line 1248 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgz5xkdbburNKfuDDh:-KwvNFY4RQQ4_tD4CMw0:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/sql/starter/xcolab-schema.sql#L1248)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

There are two terminating semi-colons here.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java, line 127 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrM95h1cOQvNHFtAYT:-KwvOk8_jQF7irqbOosG:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java#L127)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

I know this is probably copied from another tab that has the same behavior, but the "new" way of doing this is to have the handlers always return `String` and then do one of two things:
1) return `return new AccessDeniedPage(member).toViewName(response);` in case of permission error
2) return `"redirect:" + redirectUrl` if you want to redirect somewhere

After that, you can also remove the `IOException` from the throws clause above. Same applies to the other handlers.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java, line 186 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrLbtBD2gyn-afhMjP:-KwvOupvHmzlz7p5jcSv:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/TeamsTabController.java#L186)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

`PlatformTeam` should be imported.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/requests/UpdateProposalDetailsBean.java, line 25 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrNC74P6enzk4Td6pm:-KwvP685BCkWOf2uNqst:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/requests/UpdateProposalDetailsBean.java#L25)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

The variable name sounds like a prompt, I think `chosenTeam` or `selectedTeam` would be more appropriate.
</blockquote></details>

Done.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java, line 221 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh--xzSXKLuY5VG-T-:-KwvPgCRIB1gtmjkIgtv:bhkd2zm) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java#L221)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Why do we ignore this exception? It would also be better for the client methods to throw specific exceptions and to catch those separately.
</blockquote></details>

What else should we do here, if the selected team is not present in the DB? I chose this approach because some lines further up, we have this:
```
            try {
                final Proposal updatedProposal = proposalContext.getClients().getProposalClient().getProposal(proposalWrapper.getProposalId());
                p2p.setVersionTo(updatedProposal.getCurrentVersion());
                proposalContext.getClients().getProposalPhaseClient().updateProposal2Phase(p2p);
            } catch (ProposalNotFoundException ignored) {

            }
```
I think EntityNotFoundException is specific enough. We could subclass it to PlatformTeamNotFoundException, but why?

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java, line 3 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwgzsZOrWsOA49UjYjx:-KwvQJBTZj9rGQuDChP1:b-wnfmk9) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java#L3)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Looks like an accidental import.
</blockquote></details>

Done. Removed.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java, line 143 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgzn4BlXoEC45d_DHz:-KwvD6OiBEYFPStZ4Hdf:b-wnfmk9) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java#L143)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Done. Removed.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalDescriptionTabController.java, line 164 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwgzg1qx7_JCAlTZui6:-KwvD4NGJsKsTOpMBnO7:b-wnfmk9) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalDescriptionTabController.java#L164)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

(same as above - why do we need this?)
</blockquote></details>

Done. Removed.

---

*[view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/teamsTab.jspx, line 9 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-KwrNctofdf3ioY6wanX:-KwvQL6nOhqxvOe3Djib:b-896fix) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/teamsTab.jspx#L9)):*
<details><summary><i>Previously, jobachhu (Johannes Bachhuber) wrote…</i></summary><blockquote>

This looks unused.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/50)*

**Comment by jobachhu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java, line 221 at r1](https://reviewable.io:443/reviews/cci-mit/xcolab/50#-Kwh--xzSXKLuY5VG-T-:-Kx61wcuYwraiW1OtPkn:bhphme8) ([raw file](https://github.com/cci-mit/xcolab/blob/7539375badf7d566c2ad0c2fd385ad151e57bdee/view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java#L221)):*
<details><summary><i>Previously, umov wrote…</i></summary><blockquote>

What else should we do here, if the selected team is not present in the DB? I chose this approach because some lines further up, we have this:
```
            try {
                final Proposal updatedProposal = proposalContext.getClients().getProposalClient().getProposal(proposalWrapper.getProposalId());
                p2p.setVersionTo(updatedProposal.getCurrentVersion());
                proposalContext.getClients().getProposalPhaseClient().updateProposal2Phase(p2p);
            } catch (ProposalNotFoundException ignored) {

            }
```
I think EntityNotFoundException is specific enough. We could subclass it to PlatformTeamNotFoundException, but why?
</blockquote></details>

I know we often ignore these exceptions like in the snippet you found, but in most cases what we really want to do is throw a (subclass of) `RuntimeException`. These ignored blocks can often swallow up the root cause for errors, so they should be used with caution. The need to ignore these exceptions is indicative of a systemic problem: these should not be checked exceptions. We should adjust our treatment of these NotFound exceptions. In most cases, they should be unchecked (we often either re-throw these as `InternalException`s or ignore them) and otherwise using `Optional` might be a better option that using these unwieldy checked exceptions.

With that in mind, you're absolutely right in that this subclassing is quite pointless - let's not do that :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cci-mit/xcolab/50)*

**Comment by jobachhu** [comment]
Great job @umov and kudos for getting this done on a tight timeline! I'll merge this into develop as well (to indicate the _real_ closing of this PR 😃).

**Pull request merged**
